config/routes.rb
Helpdesk::Application.routes.draw do
  resources :tickets
  root to: 'tickets#index'

  match '/update_ticket' =>  'incomingmails#update', :via => :post, :as => :update_ticket
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :description, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/incomingmails_controller.rb
class IncomingmailsController < ApplicationController
  require 'mail'

  def update
    #yank out body from message
    body = params[:plain]

    Rails.logger.log Logger::INFO, params
    Rails.logger.log Logger::INFO, body.class
    Rails.logger.log Logger::INFO, body.methods
    Rails.logger.log Logger::INFO, body


    #yank out ticket id from subject
    ticket_id = get_ticket_id(params[:headers][:Subject])
    ticket = Ticket.find_by_id(ticket_id)

    if ticket
      ticket.update_attribute(:response, body)
      render :text => 'success', :status => 200
    end
  end

private
  def get_ticket_id(param)
    param.match(/<(\d*)>/)[1]
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    #get all tickets
    @tickets = Ticket.all
  end

  def new
    #create new ticket
    @ticket = Ticket.new
  end

  def create
    #find ticket
    @ticket = Ticket.new(params[:ticket])

    if @ticket.save
      TicketsMailer.new_ticket(@ticket).deliver
      flash[:notice] = "Email sent to helpdesk"
      redirect_to tickets_path
    else
      flash[:alert] = "Invalid Ticket"
      render new
    end
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomingmails_helper.rb
module IncomingmailsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<%= link_to "New Ticket", new_ticket_path %>

<% if @tickets.empty? %>
  <p>There are no tickets to display yet </p>
<% else %>
  <% @tickets.each do |ticket| %>
    <h2>Ticket <%= ticket.id %></h2>
    <p>Created by: <%= ticket.email %></p>
    <h3>Description</h3>
    <p><%= ticket.description %></p>
    <% unless ticket.response.nil? %>
      <h3>Response</h3>
      <p><%= ticket.response %></p>
    <% end %>
  <% end %>
<% end %>

app/views/tickets/new.html.erb
<%= form_for @ticket do |f| %>
  <p>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :description, "Description" %>
    <%= f.text_field :description %>
  </p>

  <%= f.submit "Create New Ticket" %>
<% end %>